from app.api.users import router as user_router
from app.api.auth import router as auth_router
from app.api.projects import router as project_router
from app.api.branches import router as branch_router
from app.api.timelogs import router as timelog_router
from app.api.task_types import router as task_type_router
from app.api.roles import router as role_router
from app.api.user_201_files import router as user201_router
from app.api.document_types import router as document_type_router
from app.api.notifications import router as notification_router
from app.api.leave_credits import router as leave_credit_router
from app.api.customers import router as customer_router
from app.api.system_options import router as system_option_router
